language: android

jdk:
 - oraclejdk8

android:
  components:
    - extra-android-support
    - extra-android-m2repository
    - build-tools-22.0.1
    - android-22
  licenses:
    - '.+'

script:
 - ./gradlew clean assembleDebug

after_success:
 - ./gradlew testDebug --info

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
