language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.1.0
    - android-20

  licenses:
    - android-sdk-license-5be876d5

install:
  - TERM=dumb ./gradlew assembleDebug

script:
  - TERM=dumb ./gradlew testDebug --info
