language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22

  licenses:
    - android-sdk-license-5be876d5

install:
  - TERM=dumb ./gradlew assembleDebug

script:
  - TERM=dumb ./gradlew testDebug --info
